#!/bin/bash
set -e

echo "Iniciando atualização do Whaticket..."

git reset --hard HEAD
git pull

echo "Atualizando o backend..."
cd backend
npm install
rm -rf dist
npm run build
npx sequelize db:migrate
npx sequelize db:seed

echo "Atualizando o frontend..."
cd ../frontend
npm install
rm -rf build
npm run build

echo "Limpando os logs..."
cd ..
pm2 flush

echo "Reiniciando os serviços..."
pm2 restart all

echo "✅ Atualização concluída com sucesso!"
